### ISSUE TITLE
Fails to build musl.wast

### ISSUE THREAD

**Issue by cretz** [cretz/asmble#1]
Error compiling musl.wast from WASM build. Fails on function 92. Add it to the test cases.

**Comment by binji** [comment]
Interesting, I'm curious what is causing the bug -- like you said, it would be useful to add it to the spec tests.

**Comment by cretz** [comment]
Yeah, it's `$__reset_tls`, I'm digging. I have no doubt it's probably an issue w/ my impl. I'll update when I know more and likely submit a test case to the spec repo.

**Comment by cretz** [comment]
This specific issue was a problem in my stack reworker. I have an optimization that doesn't dupe mem references on the stack because many of my mem ops returns the mem. I'm sure I'll hit others as I go, but not really worth a spec test case yet.

**Comment by cretz** [comment]
I had a few problems:

* I had a bad algorithm for memory instance reuse. I didn't consider the value of having duplicate instance references on the stack. Now I do and it's fixed.
* I had a bug where my insn preprocessor that injects things on the stack didn't inject something far enough back because I had the push/pop diff count wrong for copysign.
* The JVM was mad at me for my large method size because I was constructing big byte arrays in the constructor (max method size is a JVM annoyance). I was doing it the heavy way anyways. I now store the data as a string const and obtain bytes at runtime (there is no byte array const for the JVM).

**Comment by binji** [comment]
OK, sounds good. Still interesting that you were able to pass all the spec tests without noticing these issues, though!
