### ISSUE TITLE
Failure to use WASM compiled class from a JAR

### ISSUE THREAD

**Issue by vegapit** [cretz/asmble#37]
Hello,

I have a JavaFX app that uses a Rust WASM compiled in a Class file using asmble. When I run the project from IntelliJ, the app is working fine. When I create an artifact (fat JAR) however, I am getting this error every time the interface is calling a WASM function:
```
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at wasm.WasmLinker$Ptr.put(WasmLinker.kt:44)
        at wasm.WasmLinker.ptrFromString(WasmLinker.kt:33)
        at wasm.WasmLinker.price(WasmLinker.kt:12)
        at ui.JavaFXTut.calculate(JavaFXTut.kt:43)
```
Any idea, what the problem could be?

**Comment by cretz** [comment]
Hrmm, appears [that method](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#position-int-) is only in Java 9+. I think you compiled the class file with Asmble running in Java 9+ so this:

https://github.com/cretz/asmble/blob/402b5806f67cf2ed7ce5573e2ba3418c95279474/compiler/src/main/kotlin/asmble/compile/jvm/ByteBufferMem.kt#L48

got misinterpreted to use the one on `ByteBuffer` as opposed to compiling on Java 8 which would interpret the `Buffer` one. So at runtime it looks for the Java 9+ version.

My goal with the project is to be Java 8+ compatible regardless of which version the compiler runs under, so I would consider this a bug. Granted I have not been able to work on this project in a while, so I may not be able to fix it anytime soon. But feel free to submit a patch (or, if it is the version that's the problem like I'm guessing, trying running Asmble under the same Java version you'll use the class file under).

**Comment by vegapit** [comment]
> Hrmm, appears [that method](https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#position-int-) is only in Java 9+. I think you compiled the class file with Asmble running in Java 9+ so this:
> 
> https://github.com/cretz/asmble/blob/402b5806f67cf2ed7ce5573e2ba3418c95279474/compiler/src/main/kotlin/asmble/compile/jvm/ByteBufferMem.kt#L48
> 
> got misinterpreted to use the one on `ByteBuffer` as opposed to compiling on Java 8 which would interpret the `Buffer` one. So at runtime it looks for the Java 9+ version.
> 
> My goal with the project is to be Java 8+ compatible regardless of which version the compiler runs under, so I would consider this a bug. Granted I have not been able to work on this project in a while, so I may not be able to fix it anytime soon. But feel free to submit a patch (or, if it is the version that's the problem like I'm guessing, trying running Asmble under the same Java version you'll use the class file under).

I see, but I am really not sure it is a compiling issue. How could the [application work well](http://www.vegapit.com/article/javafx-gui-rust-webassembly-asmble-kotlin) when called from the IDE if it were the case? I would assume the version of the compiler used for running the program, is the one used for creating the JAR file, no?

**Comment by cretz** [comment]
> How could the application work well when called from the IDE if it were the case?

Basically, that will run anywhere (i.e. Java 9+) that has a `ByteBuffer.position()` covariant override.

>  I would assume the version of the compiler used for running the program, is the one used for creating the JAR file, no?

Not necessarily. I do not know where you are running the class where it's failing vs where it's succeeding. It is unfortunate that, due to how that code I pasted before derives the method to call at compile time, affects what is required at runtime.

While this bug exists, make sure the version of Java you are compiling with is the same as you are running with (i.e. in both `ByteBuffer.position()` needs to exist or not).

**Comment by vegapit** [comment]
You are right! IntelliJ IDEA has its own version of the jdk, that is independent from the default version installed on the machine. Thanks for the help
